### PR TITLE
[PLUGIN-1734] Upgrading the driver version from 3.13.24 to 3.14.4

### PR DESCRIPTION
**Pull request by vikasrathee-cs**
Upgrading the driver version from 3.13.24 to 3.14.4 as Sink pipelines were failing due to older JDBC version.
https://cdap.atlassian.net/browse/PLUGIN-1734

### CODE REVIEW

**Comment by MrRahulSharma** [comment]
Please add more details in the description about the change(intent behind the change).

**Comment by vikasrathee-cs** [comment]
> Please add more details in the description about the change(intent behind the change).

Added the ticket reference with error thrown by the APIs

**Comment by MrRahulSharma** [comment]
Please validate any regressions in CDF due to driver behavior change between versions. 
Driver release notes: https://community.snowflake.com/s/article/JDBC-Driver-Release-Notes

**Review by MrRahulSharma — APPROVED** [review]
Approving after successful regression testing for upgrade.

**Pull request merged**
